### ISSUE TITLE
How to display on page

### ISSUE THREAD

**Issue by kikkiraj** [indrimuska/google-maps-api-typings#1]
I followed your readme and all makes sense, I am able to install the app and i am able to see the data in my console. Now how to use the data and show a map on the page, Please help

**Comment by indrimuska** [comment]
Hi @kikkiraj,
I think you are confusing the Google Maps [JAVASCRIPT API](https://developers.google.com/maps/documentation/javascript) vs. [NODEJS API](https://github.com/googlemaps/google-maps-services-js).

In the Node.js you don't have any map :)
