### ISSUE TITLE
Publish typings to DefinitelyTyped

### ISSUE THREAD

**Issue by lukas-zech-software** [indrimuska/google-maps-api-typings#3]
Can you publish these typings to DefinitelyTyped?

I replaced my self-hacked typings with yours, and they are so much better and, at least for what I use, complete.

I'd really love to see these on DefinitelyTyped.

If you need help publishing, I'll gladly assist

**Comment by sja** [comment]
Is there any pending PR about this at DefinitelyTyped?

**Comment by indrimuska** [comment]
Yes, please refer to this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29625

**Comment by indrimuska** [comment]
Good news, the declaration has been merged into the DefinitelyTyped repo!

Feel free to open any issue here if you face any problem!

Thanks!
